name: "Feature Request"
description: Create a new ticket for a new feature request
title: "[Feature Request] "
labels: [ "feature request" ]
body:
  - type: textarea
    attributes:
      label: Overview
      description: Please describe the feature you'd like to see implemented.
    validations:
      required: true