name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Check & assembleDebug
        run: |
          ./gradlew check
          ./gradlew assembleDebug
